### ISSUE TITLE
Option to store media in subfolders and limit in each folder for faster performance

### ISSUE THREAD

**Issue by pankajvaghela** [optixsolutions/laravel-media#16]
Currently it creates folder for every media. But when there folder count gets too much it'd get very slow for system.

Please add functionality to divide them into subfolder .

For eg. If we have 25000 entries 
Then it would be better to have 250 folder with 100 media folders in each than 
25000 folders in just one folder.

So maybe provide option in config to divide them in subfolders and limit them .

**Comment by Jack97** [comment]
Can't see why this would cause a performance issue, but this should already be possible by overwriting the default media model. `config('media.model')`

You can overwrite the `getDirectory` method to upload every 100 media items into their own root directory.

```php
class Media extends BaseMedia
{
    public function getDirectory()
    {
        $id = $this->getKey();
        $number = $id - 1;

        $modulo = $number % 100;
        $number += 100 - $modulo;

        return $number.'/'.$id;
    }
}
```

If the media item's id is `33`, it will be uploaded to the `100/33` directory.

Whereas if the media item's id is `101`, it will be uploaded to the `200/101` directory.

Hope this helps!

**Comment by pankajvaghela** [comment]
Yeah that'd work. thanks. ❤️
