### ISSUE TITLE
Option to delete source media after conversion?

### ISSUE THREAD

**Issue by chrispage1** [optixsolutions/laravel-media#26]
Hi,

Is there a way for me to delete the original after the conversion process has completed? And would doing so have any known side effects?

The problem I'm having is that we're syncing off to Amazon S3, the largest of conversions result in about 300kb, but the source images are ~22mb! Just sat there wasting space!

Thanks,
Chris.

**Comment by Jack97** [comment]
Hi Chris,

There's currently no way to do this as new conversions are generated from the source image.

I admit, it would be really useful to be able to intercept the upload of the original image to allow it to be compressed. Perhaps we could add a method to the MediaUploader class to allow you to perform conversions on the source image. Either that or accept a stream / file path as source so you can manipulate the image manually before passing it to the uploader.

In the mean time I'd suggest making a scheduled job that queries the media table, looking for media >= some max size. Then foreach the results, load the source image of the media item - compress it, and save the manipulated image to the source location. Finally update the size in the database to the size of the compressed image.

Hope this helps,
Jack

**Comment by chrispage1** [comment]
Thanks Jack - I'll get a cron task going for the time being. Appreciate your help!

Chris.

**Comment by Jack97** [comment]
I'm closing this one for now - I'll consider the option to intercept source file upload in the next version.
