### ISSUE TITLE
Order (Sort) example or improved documentation

### ISSUE THREAD

**Issue by uemil** [optixsolutions/laravel-media#30]
HI, tested you package, it's pretty much exacly what I was looking for, except the documentation regarding the order of media, in the whole documentation there is only 1 line mentioning it. I couldn't figure it out how it works. Care to clarify on that? Or even better provide an example (view, controller).
Thanks.

**Comment by Jack97** [comment]
Hi @uemil,

Good to hear that you've found this package useful :)

I assume that you're talking about the order of media when it's retrieved from a model, such as `$post->media` and `$post->getMedia()` etc. If this is the case, we don't apply any specific order to the media collections by default. You can see the `media` relationship in the `HasMedia` trait simply returns a polymorphic many-to-many relationship with the media table.

If you want to apply an explicit order, you can do so by overwriting the `media` method in your model.

```php
class Post extends Model
{
    use HasMedia;

    // ...

    public function media()
    {
        return parent::media()->orderByDesc('created_at');
    }
}
```

In the above example, when retrieving media using any of the provided trait methods, the media will be ordered from newest to oldest.

I'm going to close this for now, hope this helped.

Thanks,
Jack

**Comment by uemil** [comment]
Hi, thaks for your reply, actually what I meant is how do I change the order of the media loaded, like when a client wants to order the product images in a specific order ( [ 1, 3, 5, 4, 2 ], without the need to delete all media and reupload in the desired order.
Thanks.
