### ISSUE TITLE
Add media from path

### ISSUE THREAD

**Issue by vinnygambiny** [optixsolutions/laravel-media#32]
That could be nice to have a function to add media from a path.

I have a uploader by chunk, so my media was already saved to the storage.

**Comment by joserick** [comment]
The same situation,
I have tried with the function "setFile" but without success.

**Comment by joserick** [comment]
Hello, @vinnygambiny @Jack97 
I already solved the issues in the Pull request #33 
I hope that it will be of help to you

**Comment by Jack97** [comment]
This will be addressed in the next version. See the `next` branch for more details.
