### ISSUE TITLE
Call to a member function stream() on null

### ISSUE THREAD

**Issue by getupkid** [optixsolutions/laravel-media#34]
Hello,
I am getting this error when performing conversions. I've set everything up as per the docs, but cannot work out why this is happening.

`Error
Call to a member function stream() on null`

`Optix\Media\ImageManipulator::manipulate
vendor/optix/media/src/ImageManipulator.php:64`

In my AppServiceProvider:
```
public function boot()
{
   Conversion::register("thumb", function (Image $image) {
       $image->fit(100, 100);
   });
}
```

My model:
```
public function registerMediaGroups()
{
   $this->addMediaGroup('gallery')->performConversions('thumb');
}
```

My controller: (using UploadedFile class to manipulate an uploaded file)
```
$file = new UploadedFile(
            public_path("images/test-image.jpg"),
            "test-image.jpg",
            "test-image.jpg"
);
$media = MediaUploader::fromFile($file)->upload();
$page = Page::find(1);
$page->attachMedia($media, 'gallery');
```
OR
```
$page = Page::find(1);
$media = Media::find(1);
$page->attachMedia($media, 'gallery');
```

Any help appreciated.

**Comment by getupkid** [comment]
Doesn't matter which disk I use. Even if I use the default "public" disk, it's still throwing the error.

**Comment by Jack97** [comment]
Hi @getupkid,

Sorry for just getting back to you on this.

Make sure you return the `Intervention\Image\Image` instance once you've applied the manipulations:

```php
Conversion::register('thumb', function (Image $image) {
    return $image->fit(100, 100);
});
```
