### ISSUE TITLE
Conversion After MediaUploader - No Model?

### ISSUE THREAD

**Issue by benleeth** [optixsolutions/laravel-media#37]
I am trying to create a media library where you can upload media without it being attached to any model. This is my function for saving the media:

    private function save_update_media($request)
    {
        $token = $request->input('_token');
        if(\Session::token() !== $token) {
            throw new TokenMismatchException;
        }

        $file = $request->file('file');
        $filename = Carbon::now()->timestamp . '-' . $file->getClientOriginalName();
        $name = ('' != $request->input('name')) ? $request->input('name') : preg_replace("/[\-_]/", ' ', explode('.', $file->getClientOriginalName())[0]);

        $media = MediaUploader::fromFile($file)->useFileName($filename)->useName($name)->upload();
        return $media->id;
    }

So this is a globally available media item. My issue is - How to perform any conversions after upload without attaching to a specific model?

**Comment by benleeth** [comment]
I appear to have gotten this working. 

Added this at top of Controller:
`use Optix\Media\ImageManipulator;`

This added this:
`app(ImageManipulator::class)->manipulate(
    $media, ['thumb']
);` after the `$media = MediaUploader::fromFile($file)->useFileName($filename)->useName($name)->upload();` line.

Hopefully, this helps someone or someone can tell me what I'm doing wrong.

**Comment by Jack97** [comment]
Hi @benleeth,

Thanks for updating the issue with your solution. As an alternative method, you can also dispatch the conversion creation as a job by doing the following:

```php
use Optix\Media\Jobs\PerformConversions;

PerformConversions::dispatch($media, ['thumb']);
```

I plan on adding a method to the MediaUploader class to handle this case in a future version.

Thanks,
Jack
