### ISSUE TITLE
AzureSupport ?

### ISSUE THREAD

**Issue by ubxtydev** [optixsolutions/laravel-media#38]
Does it support Azure Storage ?

**Comment by Jack97** [comment]
Hi @ubxtydev,

Thanks for taking an interest in the package.

We use Laravel's file storage module as the underlying filesystem abstraction, which in turn uses flysystem. You can setup azure by doing the following:

**Steps**

1. Extend Laravel's filesystem to provide an azure driver.

    https://laravel.com/docs/8.x/filesystem#custom-filesystems
    https://flysystem.thephpleague.com/v1/docs/adapter/azure

2. Setup a disk to use the azure driver in `config/filesystems.php`

3. Update the `media.disk` setting in `config/media.php` to the name of the azure disk you configured.

Hope this helps,
Jack
