### ISSUE TITLE
Feature table comparing to Spatie/Plank packages?

### ISSUE THREAD

**Issue by hailwood** [optixsolutions/laravel-media#4]
Hi @Jack97,

I'm interested in trying out the package since there's features I like in both the plank/mediable and spatie/media-library packages. However from the readme I'm not really seeing why I'd use this package over either of them.

I think a feature comparison table would really help!

**Comment by Jack97** [comment]
Hi @hailwood,

Thanks for your interest in the package. Good idea, i'll try and write that up today.

**Comment by Jack97** [comment]
I've added the feature table to the bottom of the documentation.
