### ISSUE TITLE
Rework media uploader class

### ISSUE THREAD

**Issue by Jack97** [optixsolutions/laravel-media#6]
I plan on reworking the `MediaUploader` class to work with a number of different sources - i.e  a file contents string, a stream or a url. This will make the class less restrictive, as currently you can only upload media from an `UploadedFile` instance.

Consider the following api:

```php
MediaUploader::fromStream($stream)->upload();
MediaUploader::fromString($string)->upload();
MediaUploader::fromUrl($url)->upload();
```

The class is also very tightly coupled with Laravel's `config` helper, which is generally considered bad practice for testing purposes. I'm contemplating accepting Laravel's `Config\Repository` - or perhaps an instance of the desired media model and target disk - in the constructor, and then binding an instance of the class to the service container. This means that it can be dependency injected or loaded via a facade. Another benefit of this would be that I could make all the `from` methods non-static.

For example:

```php
class MediaUploader
{
    protected $config;

    public function __construct(Config $config) // or (Media $model, string $disk) ?
    {
        $this->config = $config;
    }
}
```

It could then be used in your application like so:

```php
// Via a new facade
Facades\MediaUploader::fromFile($file);

// From the container
$injectedMediaUploader->fromFile($file);
```

**Comment by cached** [comment]
It would be nice if MediaUploader also accepted uploads to different type of disks. It should be handled by adding optional parameter to upload function

**Comment by Jack97** [comment]
I've been experimenting locally and a `setDisk` method will definitely be included in the next version.

I've also decided against the proposed `fromStream` and `fromString` methods in favour of a `fromPath` method so that the file reading process will be handled in the class.

**Comment by jenky** [comment]
Any updates for `setDisk` method. Of course I can do some workaround but it should be supported.

**Comment by Jack97** [comment]
@jenky I've just added that in [v0.4.0](https://github.com/optixsolutions/laravel-media/releases/tag/v0.4.0) 😄

**Comment by Jack97** [comment]
Addressed in next version, see `next` branch.
